### ISSUE TITLE
Thank you ❤️

### ISSUE THREAD

**Issue by KeironO** [imantsm/medical_abbreviations#2]
Stumbled upon this project this morning and it has made my life so much easier.

I've written a small tool to parse the files so that people that use Python can investigate their own data programmatically: https://github.com/AberystwythSystemsBiology/MEDIALpy

I've thanked you directly there, but if there's anything else you want me to add to the README or within the software as a form of acknowledgement for your hard work - just ask and I'll get it done ASAP.

Best wishes,

Keiron

**Comment by imantsm** [comment]
Thank you so much for the kind words and the acknowledgment! I'm glad that you found my thing here to be useful. I can't think of anything else for you to add. Cheers, and good luck on your endeavors!
